
import "./globals.css";
import Navbar from "./Components/Navbar";
import { Poppins } from 'next/font/google';
import Footer from "./Components/Footer";
import { SpeedInsights } from '@vercel/speed-insights/next';


const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap', // or 'auto', 'block', 'fallback', 'optional'
  variable: '--font-poppins', // A CSS variable name to reference the font
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'], // Specify desired weights
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable}`}
      >
        <Navbar />
        <main>{children}</main>
        <SpeedInsights />
        <Footer />
      </body>
    </html>
    
  );
}
